import { ComCommon } from './ComCommon';
import { ComNormal } from './ComNormal';
declare const _default: {
    tagName: string;
    bound: {};
    cm: ComCommon;
    com: ComCommon;
    comNormal: ComNormal;
    onBeforeMount(props: any, state: any): void;
    onMounted(props: any, state: any): void;
    onBeforeUpdate(props: any, state: any): void;
    onUpdated(props: any, state: any): void;
    onBeforeUnmount(props: any, state: any): void;
    onUnmounted(props: any, state: any): void;
    readonly isIOS: boolean;
    readonly isAndroid: boolean;
    readonly isMobile: boolean;
    getProp(propName: string): any;
    elementFind(tag: string): any;
    elementFindAll(tag: string): any[];
    listenToFor(el: any, pseudoEventTag: string, func: (ed: any) => {}): void;
    getElementBounds(element: any): any;
    setStyleProp(el: any, prop: string, value: number | string, unit?: string | undefined): void;
};
export default _default;
